# Generated by Django 3.2 on 2021-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_topping_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
